jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "App\\Entity"
#                path: "%kernel.project_dir%/serializer/app"
#            another-name:
#                namespace_prefix: "FOS\\UserBundle"
#                path: "%kernel.project_dir%/serializer/FOSUB"
#    services:
#        jms_serializer.object_constructor:
#            alias: jms_serializer.doctrine_object_constructor
#            public: false
