#index:
#    path: /
#    controller: App\Controller\DefaultController::index


machines:
  type: rest
  resource: App\Controller\MachineOutilController


api_login_check:
  path: /api/login
  controller: App\Controller\AuthController::login
  methods: POST

#register:
#  path: /api/register
#  controller: App\Controller\AppController::register
#  methods: POST