<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU50nYS4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU50nYS4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU50nYS4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU50nYS4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU50nYS4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U50nYS4',
    'container.build_id' => '00d1a04d',
    'container.build_time' => 1654814690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU50nYS4');
