<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5bxOD1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5bxOD1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW5bxOD1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW5bxOD1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW5bxOD1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W5bxOD1',
    'container.build_id' => '17c38b2b',
    'container.build_time' => 1654870540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5bxOD1');
